### ISSUE TITLE
Incorrect pnl

### ISSUE THREAD

**Issue by zharkomi** [eliebnn/pnl_report#4]
Try making two trades 
qty price
-2 100
1 105
Your result will be -15, however it should be -5.

Code:
df = pd.DataFrame()
df['qty'] = [-2, 1]
df['price'] = [100, 105]
df['ticker'] = ['RDSA'] * len(df['qty'])

report = PnLReport(data=df, method='fifo').run()
result = report.result_pnl
pnl = result['pnl_total']
print(pnl.values)

**Comment by eliebnn** [comment]
Hi @zharkomi - thanks for raising this. I have applied a bugfix + additional unittests: https://github.com/eliebnn/pnl_report/commit/1637a323698318d3f0f2b5b86f792509d6ce407b
